return {
  {Id=99567941238278, ScriptLink="https://raw.githubusercontent.com/FatePanda/NitrousForm/refs/heads/main/Games/InkGame.lua"};
  {Id=125009265613167, ScriptLink="https://raw.githubusercontent.com/FatePanda/NitrousForm/refs/heads/main/Games/InkGame.lua"};
  {Id=122816944483266, ScriptLink="https://raw.githubusercontent.com/FatePanda/NitrousForm/refs/heads/main/Games/InkGame.lua"};
  {Id=292439477, ScriptLink="https://raw.githubusercontent.com/FatePanda/NitrousForm/refs/heads/main/Games/InkGame.lua"};
}
